# Generated by Django 5.0.2 on 2024-02-22 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_rename_track_track1'),
        ('trainee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='track',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='track.track1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trainee/images'),
        ),
    ]
