# Generated by Django 5.0.2 on 2024-02-22 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0002_trainee_track_alter_trainee_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainee',
            old_name='track',
            new_name='track2',
        ),
    ]
