# Generated by Django 5.0.2 on 2024-02-21 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_rename_trainee_track'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Track',
            new_name='Track1',
        ),
    ]
